"""Add company_id to customers and services

Revision ID: 4e274422b54c
Revises: e3a43a1d7028
Create Date: 2026-08-12 14:10:22.498291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e274422b54c'
down_revision: Union[str, Sequence[str], None] = 'e3a43a1d7028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_customers_company_id_companies'), 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_services_name'))
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_services_company_id_companies'), 'companies', ['company_id'], ['id'])

    # Assign existing records to company 1 (RN Scanner)
    op.execute("UPDATE customers SET company_id = 1 WHERE company_id IS NULL")
    op.execute("UPDATE services SET company_id = 1 WHERE company_id IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_services_name'))
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=1)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
