"""Add category and is_deleted to services

Revision ID: 82948990ae77
Revises: c3a3b983b181
Create Date: 2026-08-04 16:31:10.447328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82948990ae77'
down_revision: Union[str, Sequence[str], None] = 'c3a3b983b181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('services', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_is_deleted'), 'services', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_is_deleted'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_column('services', 'is_deleted')
    op.drop_column('services', 'category')
    # ### end Alembic commands ###
