"""Add invoice category and tax fields

Revision ID: 93a40d2914c7
Revises: 82948990ae77
Create Date: 2026-08-04 17:02:51.841383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93a40d2914c7'
down_revision: Union[str, Sequence[str], None] = '82948990ae77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('tax_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_invoices_category'), 'invoices', ['category'], unique=False)
    op.create_index(op.f('ix_invoices_is_deleted'), 'invoices', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_is_deleted'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_category'), table_name='invoices')
    op.drop_column('invoices', 'is_deleted')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'paid_amount')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'tax_percentage')
    op.drop_column('invoices', 'category')
    # ### end Alembic commands ###
