"""Add gst and tax fields to company

Revision ID: 999b59295a29
Revises: 43b68612ca79
Create Date: 2026-08-01 19:46:13.331941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999b59295a29'
down_revision: Union[str, Sequence[str], None] = '43b68612ca79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('gst_registration', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('tax_enabled', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('default_tax_rate', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'default_tax_rate')
    op.drop_column('companies', 'tax_enabled')
    op.drop_column('companies', 'gst_registration')
    # ### end Alembic commands ###
