"""Add company_id to payment and ledger

Revision ID: acc4ccb9fd54
Revises: 93a40d2914c7
Create Date: 2026-08-04 18:24:29.849909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc4ccb9fd54'
down_revision: Union[str, Sequence[str], None] = '93a40d2914c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_customer_ledger_company_id', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_payments_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_foreign_key('fk_payments_company_id', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_company_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_is_deleted'))
        batch_op.drop_column('company_id')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('customer_ledger', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_ledger_company_id', type_='foreignkey')

    # ### end Alembic commands ###
